// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awgsmikgomxbzojpirug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3Z3NtaWtnb214YnpvanBpcnVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MjM0NjcsImV4cCI6MjA1Nzk5OTQ2N30.CaPjfgZJpU-45Xbyn24ayTY-KJzXg_QMUzdahLhcfmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);